<?php

namespace App\Tests\Repository;

use App\Entity\Movie;
use App\Repository\MovieRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class MovieTest extends KernelTestCase
{
    public $kernelBoot;
    public $container;
    public MovieRepository $movieRepository;
    public $validatorService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->kernelBoot = self::bootKernel();
        $this->container = static::getContainer();
        $this->movieRepository = $this->container->get(MovieRepository::class);
        $this->validatorService = $this->container->get("validator");
    }

    public function testRepositoryMovie() {

        $this->assertCount(2, $this->movieRepository->findAll());
    }

    public function testSearchInRepositoryMovie() {
        $result = $this->movieRepository->search("Die");

        $this->assertCount(1, $result);
    }

    /**
     * @dataProvider getListGoodMovies
     */
    public function testValidatorGoodEntityMovie($movieTitle, $movieDescription) {
        $movie = new Movie();
        $movie
            ->setTitle($movieTitle)
            ->setDescription($movieDescription)
        ;

        $errors = $this->validatorService->validate($movie);

        $this->assertCount(0, $errors);
    }

    /**
     * @dataProvider getListBadMovies
     */
    public function testValidatorBadEntityMovie($movieTitle, $movieDescription) {
        $movie = new Movie();
        $movie
            ->setTitle($movieTitle)
            ->setDescription($movieDescription)
        ;

        $errors = $this->validatorService->validate($movie);

        $this->assertCount(1, $errors);
    }


    public function getListGoodMovies() {
        return [
            ["Die Hard", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan egestas dolor, non commodo ligula vehicula at. Aliquam consectetur, ipsum nec eleifend ultricies, magna urna tincidunt tortor, sit amet blandit dolor magna non leo. Fusce ut luctus diam"],
            ["Top Gun", "Integer vel auctor est, varius congue quam. Pellentesque vestibulum dolor vitae lectus venenatis lobortis. Fusce sollicitudin nisl faucibus ante varius, non mattis felis congue. Fusce rhoncus lorem enim, ac elementum dui dictum quis. Praesent sit amet est ac justo mattis faucibus vel eu magna"]
        ];
    }

    public function getListBadMovies() {
        return [
            ["", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur accumsan egestas dolor, non commodo ligula vehicula at. Aliquam consectetur, ipsum nec eleifend ultricies, magna urna tincidunt tortor, sit amet blandit dolor magna non leo. Fusce ut luctus diam"],
            ["Top Gun", "Lorem ipsum"],
        ];
    }
}
