<?php

namespace App\Tests\Entity;

use App\Entity\Person;
use PHPUnit\Framework\TestCase;

class PersonTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub


    }

    public function testDisplayName() {
        $lastname = "Doe";
        $firstname = "John";

        $person = new Person();
        $person->setLastname($lastname);
        $person->setFirstname($firstname);

        $displayName = $lastname . " " . $firstname;

        $this->assertEquals($displayName, $person->getDisplayName());
    }





    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
